baseurl = "https://biointerns.github.io/"
languageCode = "en-us"
title = "BioInterns"
theme = "cards"

# Uncomment this to test locally
#relativeURLs = true

# quanti vuoi vederne per ogni pagina
# 6 vuol dire tipo 2 righe, con 3 cards per riga
paginate = 48

[params]
  builtBy = "Valentina Lorenzi"
  defaultImage = "gopher.jpg"

  #DISABILITATI
  #facebook = ""
  #quora = ""
  twitter = "http://twitter.com/vlorenzi3"
  github = "https://github.com/biointerns/biointerns.github.io"
  #email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  #analytics = "UA-152627751-1"
  disqus = ""
  color = "ocean"
  font = "classic"

  description = "Welcome to BioInterns! Are you an undergraduate or master's student in Biology/Biotechnology/Bioinformatics or similar? Do you study Physics/Mathematics/Informatics but have an interest in Biology? Scroll to find out about paid internship opportunities abroad at the best universities in the world."


  [params.copyright]
     name = "Valentina Lorenzi"
     link = "https://github.com/valelorenzi9"

